# Generated by Django 4.0.5 on 2024-04-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partname', models.CharField(max_length=200, unique=True)),
                ('Partcode', models.CharField(max_length=100, unique=True)),
                ('Version', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%M')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AllocatedCustomer_name', models.CharField(max_length=20)),
                ('AllocatedCustomer_country', models.CharField(choices=[('Guyana', 'Guyana'), ('Portugal', 'Portugal'), ('Ivory Coast', 'Ivory Coast'), ('Iraq', 'Iraq'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Liechtenstein', 'Liechtenstein'), ('Mali', 'Mali'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Eswatini', 'Eswatini'), ('Suriname', 'Suriname'), ('French Polynesia', 'French Polynesia'), ('El Salvador', 'El Salvador'), ('Czechia', 'Czechia'), ('Malawi', 'Malawi'), ('Syria', 'Syria'), ('Mauritius', 'Mauritius'), ('Poland', 'Poland'), ('Nepal', 'Nepal'), ('Japan', 'Japan'), ('Bolivia', 'Bolivia'), ('Chad', 'Chad'), ('France', 'France'), ('Thailand', 'Thailand'), ('French Guiana', 'French Guiana'), ('Micronesia', 'Micronesia'), ('Russia', 'Russia'), ('Comoros', 'Comoros'), ('Germany', 'Germany'), ('Brazil', 'Brazil'), ('Cuba', 'Cuba'), ('Israel', 'Israel'), ('Aruba', 'Aruba'), ('Brunei', 'Brunei'), ('Finland', 'Finland'), ('Yemen', 'Yemen'), ('Morocco', 'Morocco'), ('Papua New Guinea', 'Papua New Guinea'), ('Pakistan', 'Pakistan'), ('Vatican City', 'Vatican City'), ('Australia', 'Australia'), ('Belarus', 'Belarus'), ('Costa Rica', 'Costa Rica'), ('Benin', 'Benin'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Antarctica', 'Antarctica'), ('French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'), ('Greenland', 'Greenland'), ('Netherlands', 'Netherlands'), ('Vanuatu', 'Vanuatu'), ('Samoa', 'Samoa'), ('Ecuador', 'Ecuador'), ('Argentina', 'Argentina'), ('Denmark', 'Denmark'), ('Turkey', 'Turkey'), ('Saudi Arabia', 'Saudi Arabia'), ('Honduras', 'Honduras'), ('Timor-Leste', 'Timor-Leste'), ('Saint Lucia', 'Saint Lucia'), ('Kuwait', 'Kuwait'), ('Seychelles', 'Seychelles'), ('Uruguay', 'Uruguay'), ('India', 'India'), ('Niger', 'Niger'), ('Iceland', 'Iceland'), ('Rwanda', 'Rwanda'), ('New Zealand', 'New Zealand'), ('Spain', 'Spain'), ('Bulgaria', 'Bulgaria'), ('South Korea', 'South Korea'), ('Monaco', 'Monaco'), ('Mayotte', 'Mayotte'), ('Ireland', 'Ireland'), ('Malaysia', 'Malaysia'), ('United States', 'United States'), ('Singapore', 'Singapore'), ('Bhutan', 'Bhutan'), ('Sweden', 'Sweden'), ('Cape Verde', 'Cape Verde'), ('Kosovo', 'Kosovo'), ('Laos', 'Laos'), ('Colombia', 'Colombia'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Caribbean Netherlands', 'Caribbean Netherlands'), ('Sierra Leone', 'Sierra Leone'), ('Cyprus', 'Cyprus'), ('Kenya', 'Kenya'), ('Nicaragua', 'Nicaragua'), ('Egypt', 'Egypt'), ('Bahrain', 'Bahrain'), ('Paraguay', 'Paraguay'), ('China', 'China'), ('Nauru', 'Nauru'), ('South Georgia', 'South Georgia'), ('Tanzania', 'Tanzania'), ('Norfolk Island', 'Norfolk Island'), ('Moldova', 'Moldova'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Réunion', 'Réunion'), ('Bahamas', 'Bahamas'), ('Hungary', 'Hungary'), ('Chile', 'Chile'), ('Dominica', 'Dominica'), ('Oman', 'Oman'), ('Belize', 'Belize'), ('Guatemala', 'Guatemala'), ('Azerbaijan', 'Azerbaijan'), ('Turkmenistan', 'Turkmenistan'), ('Mozambique', 'Mozambique'), ('Nigeria', 'Nigeria'), ('Estonia', 'Estonia'), ('Myanmar', 'Myanmar'), ('Barbados', 'Barbados'), ('Armenia', 'Armenia'), ('Latvia', 'Latvia'), ('Albania', 'Albania'), ('Ethiopia', 'Ethiopia'), ('United Kingdom', 'United Kingdom'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Gibraltar', 'Gibraltar'), ('Croatia', 'Croatia'), ('Luxembourg', 'Luxembourg'), ('New Caledonia', 'New Caledonia'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Qatar', 'Qatar'), ('DR Congo', 'DR Congo'), ('Dominican Republic', 'Dominican Republic'), ('Fiji', 'Fiji'), ('Jamaica', 'Jamaica'), ('Italy', 'Italy'), ('Indonesia', 'Indonesia'), ('Sudan', 'Sudan'), ('American Samoa', 'American Samoa'), ('Cayman Islands', 'Cayman Islands'), ('Åland Islands', 'Åland Islands'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Slovenia', 'Slovenia'), ('Eritrea', 'Eritrea'), ('Zambia', 'Zambia'), ('Montenegro', 'Montenegro'), ('Senegal', 'Senegal'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Lesotho', 'Lesotho'), ('Georgia', 'Georgia'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Burundi', 'Burundi'), ('Marshall Islands', 'Marshall Islands'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Gabon', 'Gabon'), ('South Africa', 'South Africa'), ('Liberia', 'Liberia'), ('Mongolia', 'Mongolia'), ('Andorra', 'Andorra'), ('United States Virgin Islands', 'United States Virgin Islands'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Guadeloupe', 'Guadeloupe'), ('Libya', 'Libya'), ('South Sudan', 'South Sudan'), ('Hong Kong', 'Hong Kong'), ('Martinique', 'Martinique'), ('Cook Islands', 'Cook Islands'), ('Algeria', 'Algeria'), ('Haiti', 'Haiti'), ('Niue', 'Niue'), ('Romania', 'Romania'), ('Bouvet Island', 'Bouvet Island'), ('Panama', 'Panama'), ('North Macedonia', 'North Macedonia'), ('Peru', 'Peru'), ('Djibouti', 'Djibouti'), ('Bangladesh', 'Bangladesh'), ('North Korea', 'North Korea'), ('Norway', 'Norway'), ('Gambia', 'Gambia'), ('Faroe Islands', 'Faroe Islands'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Uganda', 'Uganda'), ('Uzbekistan', 'Uzbekistan'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Western Sahara', 'Western Sahara'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Ukraine', 'Ukraine'), ('Mexico', 'Mexico'), ('British Virgin Islands', 'British Virgin Islands'), ('Grenada', 'Grenada'), ('Christmas Island', 'Christmas Island'), ('Falkland Islands', 'Falkland Islands'), ('Greece', 'Greece'), ('Ghana', 'Ghana'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Isle of Man', 'Isle of Man'), ('Lithuania', 'Lithuania'), ('Burkina Faso', 'Burkina Faso'), ('Palau', 'Palau'), ('Serbia', 'Serbia'), ('Botswana', 'Botswana'), ('Taiwan', 'Taiwan'), ('Macau', 'Macau'), ('Puerto Rico', 'Puerto Rico'), ('Canada', 'Canada'), ('Republic of the Congo', 'Republic of the Congo'), ('Iran', 'Iran'), ('Namibia', 'Namibia'), ('Tajikistan', 'Tajikistan'), ('Malta', 'Malta'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Madagascar', 'Madagascar'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Switzerland', 'Switzerland'), ('Kiribati', 'Kiribati'), ('Jordan', 'Jordan'), ('Sint Maarten', 'Sint Maarten'), ('Central African Republic', 'Central African Republic'), ('Tokelau', 'Tokelau'), ('Saint Martin', 'Saint Martin'), ('Afghanistan', 'Afghanistan'), ('Zimbabwe', 'Zimbabwe'), ('Angola', 'Angola'), ('Togo', 'Togo'), ('Kazakhstan', 'Kazakhstan'), ('Pitcairn Islands', 'Pitcairn Islands'), ('Philippines', 'Philippines'), ('Cambodia', 'Cambodia'), ('Mauritania', 'Mauritania'), ('Montserrat', 'Montserrat'), ('Guam', 'Guam'), ('Belgium', 'Belgium'), ('Sri Lanka', 'Sri Lanka'), ('Venezuela', 'Venezuela'), ('Guinea', 'Guinea'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Anguilla', 'Anguilla'), ('Austria', 'Austria'), ('Curaçao', 'Curaçao'), ('Vietnam', 'Vietnam'), ('Slovakia', 'Slovakia'), ('Bermuda', 'Bermuda'), ('Somalia', 'Somalia'), ('Guernsey', 'Guernsey'), ('Solomon Islands', 'Solomon Islands'), ('United Arab Emirates', 'United Arab Emirates'), ('Jersey', 'Jersey'), ('Maldives', 'Maldives'), ('Tunisia', 'Tunisia'), ('Tonga', 'Tonga'), ('Lebanon', 'Lebanon'), ('Tuvalu', 'Tuvalu'), ('San Marino', 'San Marino'), ('Palestine', 'Palestine'), ('Cameroon', 'Cameroon')], default='', max_length=100, verbose_name='Country')),
                ('AllocatedCustomer_state', models.CharField(choices=[], default='', max_length=100, verbose_name='State')),
                ('AllocatedCustomer_district', models.CharField(choices=[], default='', max_length=100, verbose_name='District')),
                ('AllocatedCustomer_city', models.CharField(max_length=20)),
                ('AllocatedCustomer_address', models.CharField(max_length=100)),
                ('AllocatedCustomer_pincode', models.IntegerField()),
                ('AllocatedCustomer_contact', models.CharField(max_length=20)),
                ('AllocatedCustomer_email', models.EmailField(max_length=100)),
                ('AllocatedCustomer_Escalation_contact', models.CharField(max_length=20)),
                ('AllocatedCustomer_Escalation_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%M')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('Guyana', 'Guyana'), ('Portugal', 'Portugal'), ('Ivory Coast', 'Ivory Coast'), ('Iraq', 'Iraq'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Liechtenstein', 'Liechtenstein'), ('Mali', 'Mali'), ('São Tomé and Príncipe', 'São Tomé and Príncipe'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Eswatini', 'Eswatini'), ('Suriname', 'Suriname'), ('French Polynesia', 'French Polynesia'), ('El Salvador', 'El Salvador'), ('Czechia', 'Czechia'), ('Malawi', 'Malawi'), ('Syria', 'Syria'), ('Mauritius', 'Mauritius'), ('Poland', 'Poland'), ('Nepal', 'Nepal'), ('Japan', 'Japan'), ('Bolivia', 'Bolivia'), ('Chad', 'Chad'), ('France', 'France'), ('Thailand', 'Thailand'), ('French Guiana', 'French Guiana'), ('Micronesia', 'Micronesia'), ('Russia', 'Russia'), ('Comoros', 'Comoros'), ('Germany', 'Germany'), ('Brazil', 'Brazil'), ('Cuba', 'Cuba'), ('Israel', 'Israel'), ('Aruba', 'Aruba'), ('Brunei', 'Brunei'), ('Finland', 'Finland'), ('Yemen', 'Yemen'), ('Morocco', 'Morocco'), ('Papua New Guinea', 'Papua New Guinea'), ('Pakistan', 'Pakistan'), ('Vatican City', 'Vatican City'), ('Australia', 'Australia'), ('Belarus', 'Belarus'), ('Costa Rica', 'Costa Rica'), ('Benin', 'Benin'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Antarctica', 'Antarctica'), ('French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'), ('Greenland', 'Greenland'), ('Netherlands', 'Netherlands'), ('Vanuatu', 'Vanuatu'), ('Samoa', 'Samoa'), ('Ecuador', 'Ecuador'), ('Argentina', 'Argentina'), ('Denmark', 'Denmark'), ('Turkey', 'Turkey'), ('Saudi Arabia', 'Saudi Arabia'), ('Honduras', 'Honduras'), ('Timor-Leste', 'Timor-Leste'), ('Saint Lucia', 'Saint Lucia'), ('Kuwait', 'Kuwait'), ('Seychelles', 'Seychelles'), ('Uruguay', 'Uruguay'), ('India', 'India'), ('Niger', 'Niger'), ('Iceland', 'Iceland'), ('Rwanda', 'Rwanda'), ('New Zealand', 'New Zealand'), ('Spain', 'Spain'), ('Bulgaria', 'Bulgaria'), ('South Korea', 'South Korea'), ('Monaco', 'Monaco'), ('Mayotte', 'Mayotte'), ('Ireland', 'Ireland'), ('Malaysia', 'Malaysia'), ('United States', 'United States'), ('Singapore', 'Singapore'), ('Bhutan', 'Bhutan'), ('Sweden', 'Sweden'), ('Cape Verde', 'Cape Verde'), ('Kosovo', 'Kosovo'), ('Laos', 'Laos'), ('Colombia', 'Colombia'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Caribbean Netherlands', 'Caribbean Netherlands'), ('Sierra Leone', 'Sierra Leone'), ('Cyprus', 'Cyprus'), ('Kenya', 'Kenya'), ('Nicaragua', 'Nicaragua'), ('Egypt', 'Egypt'), ('Bahrain', 'Bahrain'), ('Paraguay', 'Paraguay'), ('China', 'China'), ('Nauru', 'Nauru'), ('South Georgia', 'South Georgia'), ('Tanzania', 'Tanzania'), ('Norfolk Island', 'Norfolk Island'), ('Moldova', 'Moldova'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Réunion', 'Réunion'), ('Bahamas', 'Bahamas'), ('Hungary', 'Hungary'), ('Chile', 'Chile'), ('Dominica', 'Dominica'), ('Oman', 'Oman'), ('Belize', 'Belize'), ('Guatemala', 'Guatemala'), ('Azerbaijan', 'Azerbaijan'), ('Turkmenistan', 'Turkmenistan'), ('Mozambique', 'Mozambique'), ('Nigeria', 'Nigeria'), ('Estonia', 'Estonia'), ('Myanmar', 'Myanmar'), ('Barbados', 'Barbados'), ('Armenia', 'Armenia'), ('Latvia', 'Latvia'), ('Albania', 'Albania'), ('Ethiopia', 'Ethiopia'), ('United Kingdom', 'United Kingdom'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Gibraltar', 'Gibraltar'), ('Croatia', 'Croatia'), ('Luxembourg', 'Luxembourg'), ('New Caledonia', 'New Caledonia'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Qatar', 'Qatar'), ('DR Congo', 'DR Congo'), ('Dominican Republic', 'Dominican Republic'), ('Fiji', 'Fiji'), ('Jamaica', 'Jamaica'), ('Italy', 'Italy'), ('Indonesia', 'Indonesia'), ('Sudan', 'Sudan'), ('American Samoa', 'American Samoa'), ('Cayman Islands', 'Cayman Islands'), ('Åland Islands', 'Åland Islands'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Slovenia', 'Slovenia'), ('Eritrea', 'Eritrea'), ('Zambia', 'Zambia'), ('Montenegro', 'Montenegro'), ('Senegal', 'Senegal'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Lesotho', 'Lesotho'), ('Georgia', 'Georgia'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Burundi', 'Burundi'), ('Marshall Islands', 'Marshall Islands'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Gabon', 'Gabon'), ('South Africa', 'South Africa'), ('Liberia', 'Liberia'), ('Mongolia', 'Mongolia'), ('Andorra', 'Andorra'), ('United States Virgin Islands', 'United States Virgin Islands'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Guadeloupe', 'Guadeloupe'), ('Libya', 'Libya'), ('South Sudan', 'South Sudan'), ('Hong Kong', 'Hong Kong'), ('Martinique', 'Martinique'), ('Cook Islands', 'Cook Islands'), ('Algeria', 'Algeria'), ('Haiti', 'Haiti'), ('Niue', 'Niue'), ('Romania', 'Romania'), ('Bouvet Island', 'Bouvet Island'), ('Panama', 'Panama'), ('North Macedonia', 'North Macedonia'), ('Peru', 'Peru'), ('Djibouti', 'Djibouti'), ('Bangladesh', 'Bangladesh'), ('North Korea', 'North Korea'), ('Norway', 'Norway'), ('Gambia', 'Gambia'), ('Faroe Islands', 'Faroe Islands'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Uganda', 'Uganda'), ('Uzbekistan', 'Uzbekistan'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Western Sahara', 'Western Sahara'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Ukraine', 'Ukraine'), ('Mexico', 'Mexico'), ('British Virgin Islands', 'British Virgin Islands'), ('Grenada', 'Grenada'), ('Christmas Island', 'Christmas Island'), ('Falkland Islands', 'Falkland Islands'), ('Greece', 'Greece'), ('Ghana', 'Ghana'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Isle of Man', 'Isle of Man'), ('Lithuania', 'Lithuania'), ('Burkina Faso', 'Burkina Faso'), ('Palau', 'Palau'), ('Serbia', 'Serbia'), ('Botswana', 'Botswana'), ('Taiwan', 'Taiwan'), ('Macau', 'Macau'), ('Puerto Rico', 'Puerto Rico'), ('Canada', 'Canada'), ('Republic of the Congo', 'Republic of the Congo'), ('Iran', 'Iran'), ('Namibia', 'Namibia'), ('Tajikistan', 'Tajikistan'), ('Malta', 'Malta'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Madagascar', 'Madagascar'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Switzerland', 'Switzerland'), ('Kiribati', 'Kiribati'), ('Jordan', 'Jordan'), ('Sint Maarten', 'Sint Maarten'), ('Central African Republic', 'Central African Republic'), ('Tokelau', 'Tokelau'), ('Saint Martin', 'Saint Martin'), ('Afghanistan', 'Afghanistan'), ('Zimbabwe', 'Zimbabwe'), ('Angola', 'Angola'), ('Togo', 'Togo'), ('Kazakhstan', 'Kazakhstan'), ('Pitcairn Islands', 'Pitcairn Islands'), ('Philippines', 'Philippines'), ('Cambodia', 'Cambodia'), ('Mauritania', 'Mauritania'), ('Montserrat', 'Montserrat'), ('Guam', 'Guam'), ('Belgium', 'Belgium'), ('Sri Lanka', 'Sri Lanka'), ('Venezuela', 'Venezuela'), ('Guinea', 'Guinea'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Anguilla', 'Anguilla'), ('Austria', 'Austria'), ('Curaçao', 'Curaçao'), ('Vietnam', 'Vietnam'), ('Slovakia', 'Slovakia'), ('Bermuda', 'Bermuda'), ('Somalia', 'Somalia'), ('Guernsey', 'Guernsey'), ('Solomon Islands', 'Solomon Islands'), ('United Arab Emirates', 'United Arab Emirates'), ('Jersey', 'Jersey'), ('Maldives', 'Maldives'), ('Tunisia', 'Tunisia'), ('Tonga', 'Tonga'), ('Lebanon', 'Lebanon'), ('Tuvalu', 'Tuvalu'), ('San Marino', 'San Marino'), ('Palestine', 'Palestine'), ('Cameroon', 'Cameroon')], default='', max_length=100, verbose_name='Country')),
                ('state', models.CharField(choices=[], default='', max_length=100, verbose_name='State')),
                ('district', models.CharField(choices=[], default='', max_length=100, verbose_name='District')),
                ('pincode', models.IntegerField()),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('Escalation_contact', models.CharField(max_length=20)),
                ('Escalation_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Drone_id', models.CharField(max_length=20, unique=True)),
                ('UIN', models.CharField(max_length=20, unique=True)),
                ('drone_type', models.CharField(choices=[('1', 'None'), ('2', 'Service'), ('3', 'Sold'), ('4', 'Training'), ('5', 'Others')], default=1, max_length=20)),
                ('AVB', models.CharField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/media/image/product/')),
                ('spec', models.FileField(upload_to='static/documents/product/')),
                ('description', models.TextField()),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/media/image/model/')),
                ('spec', models.FileField(upload_to='static/documents/product/')),
                ('description', models.TextField()),
                ('created_on', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dispatch_list', models.FileField(upload_to='static/documents/dispatch/')),
                ('handover_doc', models.FileField(upload_to='static/documents/handover/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drone')),
                ('primary_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
                ('secondry_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allocatedcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ECN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release', models.CharField(max_length=100)),
                ('expertise', models.CharField(choices=[('1', 'None'), ('2', 'Pilot'), ('3', 'Technician'), ('4', 'Ops_Engineer'), ('5', 'Support_agent'), ('6', 'Developers')], default=1, max_length=10)),
                ('type', models.CharField(choices=[('1', 'None'), ('2', 'Software'), ('3', 'Hardware'), ('4', 'QC'), ('5', 'Others')], default=1, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('1', 'None'), ('2', 'Planner'), ('3', 'Embedded'), ('4', 'Ga_app'), ('5', 'FCS'), ('6', 'Hardware'), ('7', 'Other')], default=1, max_length=50)),
                ('release_by', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('desc', models.CharField(max_length=1000)),
                ('sop', models.FileField(upload_to='static/documents/SOP/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('applicable_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='allocatedcustomer',
            name='primary_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
