# Generated by Django 4.0.5 on 2022-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partname', models.CharField(max_length=200, unique=True)),
                ('Partcode', models.CharField(max_length=100, unique=True)),
                ('Version', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%M')),
            ],
        ),
    ]
