# Generated by Django 4.0.5 on 2024-04-19 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
