# Generated by Django 4.0.5 on 2024-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sop_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecn',
            name='desc',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sop',
            name='desc',
            field=models.TextField(max_length=2000),
        ),
    ]
