# Generated by Django 4.0.5 on 2024-04-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sop_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Drone_base_version', models.CharField(max_length=20)),
                ('CC_base_version', models.CharField(max_length=20)),
                ('FCS_base_version', models.CharField(max_length=20)),
                ('BLL_base_version', models.CharField(max_length=20)),
                ('drone_current_version', models.CharField(max_length=20)),
                ('CC_current_version', models.CharField(max_length=20)),
                ('FCS_current_version', models.CharField(max_length=20)),
                ('BLL_current_version', models.CharField(max_length=20)),
                ('Available_Drone_version', models.CharField(blank=True, max_length=100)),
                ('Available_CC_version', models.CharField(blank=True, max_length=100)),
                ('Available_FCS_version', models.CharField(blank=True, max_length=100)),
                ('Available_BLL_version', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drone',
            name='BLL_base_version',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='CC_base_version',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='Drone_base_version',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='FCS_base_version',
        ),
        migrations.DeleteModel(
            name='DroneConfigration',
        ),
        migrations.AddField(
            model_name='droneconfiguration',
            name='drone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drone'),
        ),
    ]
